### ISSUE TITLE
Healbot Config2 - Reraise IV

### ISSUE THREAD

**Issue by Heretic6667** [Icydeath/HealbotConfigurator2#1]
Hello - any chance Reraise IV can be added to the buff UI?  Thanks :)

Edit: it seems multiple job point abilities such as Refresh III and Temper II are also excluded from the buff UI.  Perhaps all?

**Comment by Icydeath** [comment]
Hmm, could you try clicking the drop down and type in Reraise IV and then click Add
Just curious if that could be a temp fix until I add in the job point spells.

Thanks for reporting the issue!

**Comment by Icydeath** [comment]
I see the issue, i'll build and release soon. Thanks again

**Comment by Heretic6667** [comment]
The temp fix works :) appreciate the new release as well!

**Comment by Icydeath** [comment]
Released [v1.1](https://github.com/Icydeath/HealbotConfigurator2/releases/tag/v1.1)

Let me know if you have any troubles with v1.1
