### ISSUE TITLE
Couldn't load player name only show xiloader

### ISSUE THREAD

**Issue by comola** [Icydeath/HealbotConfigurator2#3]
Hi,

I try to use the program but somehow it just doesn't work. I only see xiloader as a option. instead of character name. I have 3 windower instance at the same time. will that be the issue? also once in a while I will see the character name but program do nothing.

please help. thank you

Also thank you for making this program.

Comola

**Comment by Icydeath** [comment]
I don't play on private servers but the code should handle it regardless.. hmm. Just to verify, are you running as Administrator? Idk if that is the issue, just want to rule it out is all.
When I get some time I'll dig into the code.

What private server are you using? Maybe I'll set that up as well for testing.
